# Generated by Django 4.0.4 on 2022-05-21 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=100)),
                ('pCategory', models.CharField(max_length=100)),
                ('pDate_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('pPrice', models.IntegerField()),
                ('pColor', models.CharField(max_length=100)),
                ('pImage1', models.ImageField(default='default.jpg', upload_to='product_pics')),
                ('pImage2', models.ImageField(default='default.jpg', upload_to='product_pics')),
                ('pImage3', models.ImageField(default='default.jpg', upload_to='product_pics')),
                ('pRating', models.IntegerField()),
                ('pOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('pMobileProcessor', models.CharField(max_length=100)),
                ('pMobileRearCamera', models.CharField(max_length=100)),
                ('pMobileFrontCamera', models.CharField(max_length=100)),
                ('pMobileDisplay', models.CharField(max_length=100)),
                ('pMobileRam', models.CharField(max_length=100)),
                ('pMobileStorage', models.CharField(max_length=100)),
                ('pMobileBattery', models.CharField(max_length=100)),
                ('pMobileOS', models.CharField(max_length=100)),
            ],
            bases=('product.product',),
        ),
    ]
